### ISSUE TITLE
Unable to decode configuration Recovery suggestion: Make sure the plugin configuration is JSONValue

### ISSUE THREAD

**Issue by jiangqinglianSNQU** [aws-amplify/amplify-ios#1788]
### Describe the bug

The question is "Unable to decode configuration
Recovery suggestion: Make sure the plugin configuration is JSONValue" and "Storage category is not configured. Call Amplify.configure() before using any methods on the category."

The code as follow:
```
do {
        try Amplify.add(plugin: AWSCognitoAuthPlugin())
        try Amplify.add(plugin: AWSS3StoragePlugin())
        try Amplify.configure(self.amplifyConfig())
        print("Amplify configured with storage plugin")
    } catch {
        print("Failed to initialize Amplify with \(error)")
    }
```

How do i set the config?

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. download Amplify framework
2. write code as follow:
   import Amplify
   import AWSS3StoragePlugin
   import AWSCognitoAuthPlugin

   func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        do {
            try Amplify.add(plugin: AWSCognitoAuthPlugin())
            try Amplify.add(plugin: AWSS3StoragePlugin())
            try Amplify.configure(self.amplifyConfig())
            print("Amplify configured with storage plugin")
        } catch {
            print("Failed to initialize Amplify with \(error)")
        }
        
        
        return true
    }
3. command run
4. print error in conslelog
```

### Expected behavior

Am I misconfigured?
 How do I set it up? 
I was following the documentation. Did I miss any key information?
I hope run correct 

### Amplify Framework Version

1.24.0

### Amplify Categories

Auth, Storage

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

8.1.0

### Xcode version

13.3.1

### Relevant log output

```shell
Failed to initialize Amplify with PluginError: Unable to decode configuration
Recovery suggestion: Make sure the plugin configuration is JSONValue

Fatal error: Storage category is not configured. Call Amplify.configure() before using any methods on the category.

Amplify/StorageCategory.swift:19: Fatal error: Storage category is not configured. Call Amplify.configure() before using any methods on the category.
```

### Is this a regression?

No

### Device

did't run done!!

### iOS Version

iOS 13.4

### Specific to simulators

iPhone 13 Pro Max

### Additional context

waiting for reply， thank you

**Comment by atierian** [comment]
Hi @jiangqinglianSNQU, thanks for opening this issue.
You'll need to use Amplify CLI to create the backend resources that Auth and Storage need. This creates `amplifyconfiguration.json` and `awsconfiguration.json` files that Amplify needs to be configured properly.
Here are a few links to relevant documentation that will guide you through the process.
[General Getting Started Guide](https://docs.amplify.aws/start/getting-started/installation/q/integration/ios/)
[Auth Getting Started Guide](https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios/)
[Storage Getting Started Guide](https://docs.amplify.aws/lib/storage/getting-started/q/platform/ios/)

Let us know if you have any other questions after going through the guides.

**Comment by jiangqinglianSNQU** [comment]
I am in accordance with the operations on the document, but always failed operation, is unable to correctly generate amplifyconfiguration.json and awsconfiguration.json file, or you don't these two files, or the file content is empty
Do you know the API for setting accessid, accessSecret, and Token?

**Comment by atierian** [comment]
> but always failed operation
Can you please specify what this means. 
What is failing?
What error message are you seeing?

**Comment by jiangqinglianSNQU** [comment]
`AccessDeniedException: User: arn:aws:iam::426315288917:user/s3user is not authorized to perform: amplify:CreateApp on resource: arn:aws:amplify:ap-northeast-1:426315288917:apps/*
    at Object.extractError (/snapshot/repo/build/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/snapshot/repo/build/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
    at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/snapshot/repo/build/node_modules/aws-sdk/lib/event_listeners.js:335:13)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'AccessDeniedException',
  time: 2022-05-12T12:03:15.441Z,
  requestId: '1e812e64-2f91-4cf4-bab9-0c8657aeb9e5',
  statusCode: 403,
  retryable: false,
  retryDelay: 38.36087606117611
}
`
It was tell me "Authorization failure";I use a temporary Token and accessKeyId and secretAccessKey  for uploading authentication. How do I dynamically configure them?

**Comment by atierian** [comment]
You'll need to follow the steps on this [guide](https://docs.amplify.aws/start/getting-started/installation/q/integration/ios/#install-and-configure-the-amplify-cli) exactly.
Have you done that, and if so, what was the result of `amplify configure`?
