### ISSUE TITLE
amplify-tools failed to pick up `amplify` after installation

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#387]
**Describe the bug**
My system is on 4.12.0 of Amplify CLI
```
> amplify --v
4.12.0
> which amplify
/Users/mdlaw/bin/amplify
```
when i use the amplify-tools pod, it tries to install 4.18.0, looks like it was successfully, and then fails to use it, eg. 
```
Error: spawn amplify ENOENT
    ...
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn amplify',
  path: 'amplify',
  spawnargs: [ 'init', '--quickstart' ]
}
```
**To Reproduce**
1. `pod "amplify-tools"` picks up 0.2.0 version of the pod
2. open xcworkspace and build
3. Build fails with error
```
(not in PATH env variable)
😟 Amplify CLI was not found.
😅 Installing Amplify CLI. Hold tight.
npm WARN deprecated graphql-tools-fork@9.0.1: graphql-tools-fork has been merged into upstream graphql-tools@5
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/Users/mdlaw/temp/api9/api9/bin/amplify -> /Users/mdlaw/temp/api9/api9/lib/node_modules/@aws-amplify/cli/bin/amplify

> core-js@3.6.5 postinstall /Users/mdlaw/temp/api9/api9/lib/node_modules/@aws-amplify/cli/node_modules/amplify-graphql-types-generator/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m

[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
[96m>[94m https://opencollective.com/core-js [0m
[96m>[94m https://www.patreon.com/zloirock [0m

[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m


> core-js@2.6.11 postinstall /Users/mdlaw/temp/api9/api9/lib/node_modules/@aws-amplify/cli/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@3.0.2 postinstall /Users/mdlaw/temp/api9/api9/lib/node_modules/@aws-amplify/cli/node_modules/ejs
> node --harmony ./postinstall.js

Thank you for installing [35mEJS[0m: built with the [32mJake[0m JavaScript build tool ([32mhttps://jakejs.com/[0m)


> @aws-amplify/cli@4.18.0 postinstall /Users/mdlaw/temp/api9/api9/lib/node_modules/@aws-amplify/cli
> node scripts/post-install.js



----------------------------------------
Successfully installed the Amplify CLI
----------------------------------------


JavaScript Getting Started - https://aws-amplify.github.io/docs/js/start


Android Getting Started - https://aws-amplify.github.io/docs/android/start


iOS Getting Started - https://aws-amplify.github.io/docs/ios/start


npm WARN inquirer-autocomplete-prompt@1.0.2 requires a peer of inquirer@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-compat@3.5.1 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

+ @aws-amplify/cli@4.18.0
added 1049 packages from 717 contributors in 86.741s
✅ Successfully installed Amplify CLI.
🎸 Creating base Amplify project
events.js:282
      throw er; // Unhandled 'error' event
      ^

Error: spawn amplify ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn amplify',
  path: 'amplify',
  spawnargs: [ 'init', '--quickstart' ]
}
Command PhaseScriptExecution failed with a nonzero exit code
```

**Environment(please complete the following information):**
 - amplify-tools 0.2.0 via cocoapods

```
> node -v
v13.5.0
> which node
/usr/local/bin/node
```

**Comment by drochetti** [comment]
@lawmicha do you know if this is still reproducible in [v1.0.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.0.0)?

**Comment by drochetti** [comment]
@lawmicha just to clarify, do you use NVM in your environment? This can be related to #535

**Comment by lawmicha** [comment]
> @lawmicha just to clarify, do you use NVM in your environment? This can be related to #535

I'm not using NVM. I think i have always seen issues where Amplify CLI upgrade were successful but does not upgrade. It is most likely something with my system rather than Amplify Tools
